services:
  app:
    image: ghcr.io/filbot/bart-proxy:latest
    restart: unless-stopped
    container_name: bart-proxy
    volumes:
      - ./gtfs-static-data:/app/gtfs-static-data
    environment:
      TZ: "America/Los_Angeles"
    networks:
      - proxy

networks:
  proxy:
    external: true
